version: '3.7'

services:

  vue:
    container_name: meetingroom-frontend
    image: meetingroom-frontend-vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'

# docker-compose up -d --build